### ISSUE TITLE
节点无法连线

### ISSUE THREAD

**Issue by zhongxi-tech** [lchrennew/dragonfly-dag#1]
如标题？

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lchrennew** [comment]
请发一下你的代码

**Comment by zhongxi-tech** [comment]
> 请发一下你的代码

代码在app.vue里面

**Comment by lchrennew** [comment]
> > 请发一下你的代码
> 
> 代码在app.vue里面

我已经定位到原因了

**Comment by lchrennew** [comment]
问题已经修复

**Comment by zhongxi-tech** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lchrennew/dragonfly-dag"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月16日(星期五) 上午8:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lchrennew/dragonfly-dag] 节点无法连线 (#1)





 
我今晚调试了一下，新建两个节点，“Hi 1”节点的绿锚点&nbsp;和&nbsp; “Hi 2”节点的红锚点还是无法连线的
